name: Flutter Linux Build and Snap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
    
    - name: Install Flutter dependencies
      run: flutter pub get
    
    - name: Enable Linux desktop
      run: flutter config --enable-linux-desktop
    
    - name: Build Linux
      run: flutter build linux --release
    
    - name: Install Snapcraft
      run: |
        sudo snap install snapcraft --classic
        sudo chown root:root /
    - name: Create snapcraft.yaml
      run: |
        mkdir -p snap
        cat << EOF > snap/snapcraft.yaml
        name: f_demo
        version: '1.0.0'
        summary: Short summary of your app
        description: |
          A longer description of your app.

        confinement: strict
        base: core22
        grade: stable

        apps:
          f_demo:
            command: f_demo
            extensions: [flutter-stable]
            plugs:
              - network

        parts:
          f_demo:
            source: build/linux/x64/release/bundle
            plugin: dump
        EOF
    
    - name: Build Snap
      run: snapcraft --destructive-mode
    
    - name: Archive Snap
      uses: actions/upload-artifact@v3
      with:
        name: snap-package
        path: '*.snap'